### ISSUE TITLE
Diagnostic Reports: Students - Individual Student

### ISSUE THREAD

**Issue by tomcalabrese** [empirical-org/Empirical-Core#1568]
Zeplin:
https://zpl.io/1W0ko9

![diagnostic reports](https://cloud.githubusercontent.com/assets/8131465/17755653/25893148-64a9-11e6-8118-a4f8cf3d4b3b.png)

- [ ] Revise the title copy once closer to launch

**Comment by RyanNovas** [comment]
Feedback
- “Diagnostic” should be in the “Student Reports” tab in-between “Overview” and “Concepts”
- Overall, there should be more vertical space in between where it says “Activity Info” and the dropdown, see the zeplin file. 
- In the main Students page, the table should be aligned left
- When you drill into an individual student the “Students” tab should be green. Right now it looks like nothing is selected.
- In the individual student results page, need to adjust the overall spacing to match the zeplin 
- For the recommendations page, it would be good if we could align the “Recommended Activity Packs” key thing to the left of “Activity Name” not to the table.
- In the recommendations page, if we could have all of the lines in the table be 1px instead of 2px.
