### ISSUE TITLE
Generate a PDF of Student Login info for Teachers

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#1785]
TenMarks provides teachers with a generated PDF that contains all of the student login info for all of the students. We could generate something like this, and enable teachers to print and share login info. 

![screen shot 2015-07-24 at 6 40 05 pm](https://cloud.githubusercontent.com/assets/3667179/8887372/7c5375a0-3233-11e5-833d-e742022408c2.png)

![screen shot 2015-07-24 at 6 40 18 pm](https://cloud.githubusercontent.com/assets/3667179/8887375/88645c9c-3233-11e5-9b2b-e0b5a959f5b8.png)

![screen shot 2015-10-02 at 8 35 55 pm](https://cloud.githubusercontent.com/assets/3667179/10261291/3c9c0eb0-6945-11e5-8219-6ef442942b59.png)

**Comment by jaredsilver** [comment]
This is mostly done except for tests and some formatting, but I have a couple implementation questions.

1. For passwords, do we just want it to say the student's last name as the default password? From what I see in Rails console, it seems the passwords are encrypted so that might be the only option?

2. Do we want any sort of fun formatting/design, or do we want to keep it pretty barebones? I can either make it match the image in the issue, or I can play around with some other stuff if you want.

Here's what it looks like right now:
![quill-pdf](https://cloud.githubusercontent.com/assets/1312199/20234399/c9f85582-a848-11e6-9142-3a6958e89ed0.png)

**Comment by jaredsilver** [comment]
Here's what it looks like now:

![quill-login-pdf](https://cloud.githubusercontent.com/assets/1312199/20234774/9e693754-a84f-11e6-8912-d8cea54713b1.png)
