### ISSUE TITLE
Updates to "Our Story" pages. 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#2057]
Bump up the text to 16 point on the mission page and the impact page.  
Consider making about, impact, team, news pages white. 
Drop the sub-nav bar when there is no sub-nav present. The only page that needs sub-nav is impact.

**Comment by amr-quill** [comment]
- [] Let's increase the font size of the text of the body under titles in the About page to 16px and a line height of 1.8
- [] Let's make the background of the About, Impact, Team, and News pages white
- [] Remove the sub-nav bar + gray line when there no sub-nav links. The only page that needs sub-nav is Impact because it has sub nav links.
