### ISSUE TITLE
Edits to Editing Units 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#2066]
# Edit Activity Pack Name 
- [ ] make the minimum the number of characters of the unit. 
- [x] Text Entry 300 Pixels by default.

# Adding Activity
- [ ] Add anchor links to units once you save. 
- [x] change title: Add Additional Activities to [Name of Activity Pack]
- [x] sub-nav:show the sub-nav into the top-level routing.
- [x] the button is grey by default, turns green once an action happens, and turns to grey with the spinner once. 

# Edit Students Page
- [x] Add title: Edit Students for [Unit Name]
- [x] button font is too big. 
- [x] Show the button as grey by default with the text "Edit Students to Save"
- [x] once an edit action happens, change it to green with its current text.
- [x] once you press, save, change the text to "Saving" make it grey, show the spinner, and lock the button.  
- [x] need sub-nav here as well. 

# My Activity packs
- [x] Edit Students text should not be bold.
- [x] Change the buttons from trash cans to x buttons (same as activity planner). 
- [x] Move the "select due date" sixty pixels to the right.

**Comment by RyanNovas** [comment]
@petergault there are two features from here which I don't think are worth the time and are outstanding.

The first one is dyanimically setting the input width when editing units -- input boxes don't allow this by default, and I don't think it is worth introducing the custom JS it would require for an extreme edgecase.

Second is the anchor links -- since everything is already hashed in react router, this gets weird. I've found a few hacky ways to do this, but would rather not implement them. If I come across a good package for doing so, or have some downtime, I will revisit.
