### ISSUE TITLE
Premium Through 2018 School Year

### ISSUE THREAD

**Issue by RyanNovas** [empirical-org/Empirical-Core#2183]
All subscriptions from now through July 1, 2017 should expire July 1, 2018.

To do this, make sub expiration date be the later of `Date.today + 365` or July 1, 2018 in app/models/subscription.rb

To do this, we need
- email
- splash page
- intercom
- premium page update
- change premium card to mention it
- Google Adwords showing promo

**Comment by petergault** [comment]
Premium Review:
1. Update pricing page - buy now, get it for next year. We put it up in march of each year. Add as a bar. 
2. Add school pricing at $500 per school. 
3. Give teachers the option to either pay online or request an invoice. 
4. Add a new tier or section below for districts - multiple schools or a district purchasing? Contact us?

Email Blasts 
1. We email all subscribers a plaintext email - interested in Quill Premium? Get it for your school for $500. 
2. We email all teachers who purchased since January. You get it now. Refund for you if your school as well. Discount for you if your school buys it? 
3. We email all previous premium subscribers. Get an extension now for a discount. 

Intercom
Update intercom drip with pricing.

**Comment by amr-quill** [comment]
I have put up comments on the zeplin screen

Zeplink: https://zpl.io/Xewld
