### ISSUE TITLE
Add Customizability to Activity Pack Descriptions

### ISSUE THREAD

**Issue by Hannahmonk** [empirical-org/Empirical-Core#2236]
- [x] Add the ability to define the titles/headings of sections in activity pack descriptions

- [x] Add the ability to create line breaks in the text boxes of each section

- [x] Add additional sections to the activity pack descriptions (either the ability to add new sections while editing the activity pack, or just code in one or two more sections)

**Comment by ddmck** [comment]
OK, we are going to go with Markdown for this. Use this Lib https://github.com/rexxars/react-markdown

We should add one new field to the model called pack_info. It should be of type text, NOT STRING.

The form for creating/editing packs should have a new text area added that staff can write the markdown. Next to this text area should be a real time version of the output of the text area. Simply pass in the current value of the text area into the markdown component.

Above the text area link to a markdown cheatsheet.

Update the pack pages to show the packInfo only is it is present. Otherwise, display the old content.
We will deprecate the old content when we can have someone port it over.
