### ISSUE TITLE
Make sure Clever users are added to a school when they sign up.

### ISSUE THREAD

**Issue by ddmck** [empirical-org/Empirical-Core#2889]
- [x] Investigate if school can be found in database from clever payload
- [x] Create the schools users entry if so.

**Comment by jaredsilver** [comment]
Currently, we are using `find_or_create_by` logic to find or create a new school based only on the name of the school.

This is problematic because the name of a school coming from Clever's API is rarely the same as the name of a school coming from our NCES imports, which means we have duplicate schools, teachers associated with the wrong schools, and schools not associated with the right districts.

To remedy this problem:

1. If the Clever API returns an NCES ID, then attempt to find a school in our database with that same NCES ID.
2. If the Clever API does not return an NCES ID, or if the NCES ID does not match one in our database, attempt to fuzzy match to schools in our database based on other information that Clever might return (e.g. addresses / zip codes) and display these options to the user to select from.
3. Finally, if we can't find any matches, display the normal school selector modal we use elsewhere.
