### ISSUE TITLE
Unable to run servers 3001, 8080 in local

### ISSUE THREAD

**Issue by ganisivakumar** [empirical-org/Empirical-Core#3488]
Hi, When i click on diagnostic test, it is redirecting me to localhost:3001.Can you help me how i can 
run that server.

**Comment by jaredsilver** [comment]
Hi @ganisivakumar -- the activities use separate services, some of which have yet to be open sourced. In the meantime, because this project works independently of those, a lot of small issues can still be addressed without interacting with them. We're working on creating a better workflow for contributors, but for now this is where we're at unfortunately. Feel free to ping me via email (jared@quill.org) if there's a particular issue you're interested in tackling. Otherwise, we recommend checking back in about a month, when we hope to have this resolved. Thanks for your interest in the project! 😄
