### ISSUE TITLE
Premium page: followup issue

### ISSUE THREAD

**Issue by amr-thameen** [empirical-org/Empirical-Core#3954]
## The first two checkboxes have been started on `feat/one-view-checkout`

- [ ] No need for the Enter Credit Card, we should automatically send them to the stripe modal if they don't have a credit card (Teachers and Schools)
- [ ] The stripe modal has a button that says Enter Card Details, shouldn't it be Buy Now? Also, can we make the subtitle "$80 for one-year of Teacher Premium" instead of "Enter Your Credit Card"

**For Later:**
- [ ] Purchase should send teachers to this modal: zpl.io/a8yA61g, we are currently sending them to the modal to renew with "Not purchaser information" I think we should make it simpler
- [ ] "New subscribers! Upgrade now and get the rest of this school year for free, extending your subscription through July 31, 2019." 

<img width="1130" alt="screen shot 2018-03-06 at 10 19 54 am" src="https://user-images.githubusercontent.com/25299820/37040567-2e7aba00-2128-11e8-9460-91d644cfa6d6.png">

**Comment by RyanNovas** [comment]
@amr-thameen For the first two (- [ ] No need for the Enter Credit Card, we should automatically send them to the stripe modal if they don't have a credit card (Teachers and Schools)
- [ ] The stripe modal has a button that says Enter Card Details, shouldn't it be Buy Now? Also, can we make the subtitle "$80 for one-year of Teacher Premium" instead of "Enter Your Credit Card")

This would involve a significant code overhaul that I do not think is worth it as part of this project to save on click. These are deeply nested and this would take substantial recoding and complexity.

- [ ] Purchase should send teachers to this modal: zpl.io/a8yA61g, we are currently sending them to the modal to renew with "Not purchaser information" I think we should make it simpler -- @amr-thameen isn't this by design?
