### ISSUE TITLE
Get Dev DB on Docker

### ISSUE THREAD

**Issue by RyanNovas** [empirical-org/Empirical-Core#4109]
Currently we have a Digital Ocean droplet running docker with a Postgres image.

We need to:

1. Figure out how best to SSH in from our local Empirical Core apps to the PG database.
2. Document ^^
3. Build a chron job to pull the prod db from production to the Dockerized PG instance.
4. Write a dockerfile to do all the above.

General notes are located here: https://docs.google.com/document/d/1wTAiv-Ph3tVuuYsqP2uZMJDp82kaPLVsuh8q-brD5yc/edit#

**Comment by buckmaxwell** [comment]
Split into issues:

1. Set up SSH Tunnel from Ryan's MacBook Pro to digital ocean droplet
2. Use autossh and launchd to continuously renew this connection.
3. Make a new postgres user named ryan with a password
4. Make a new database named ryan-dev-db with owner ryan
5. Clone the production database into ryan-dev-db
6. Test long running functions / monitor memory / configure digital ocean droplet and docker for optimal performance
7. Document steps 1 - 6 so that other devs can connect to their own dev databases
8. Ensure all current devs have access to their dev database (either because they set it up themselves using the guide created in 7 or because Ryan or Max set them up or helped).
