### ISSUE TITLE
Require First and Last Name for Teachers

### ISSUE THREAD

**Issue by RyanNovas** [empirical-org/Empirical-Core#414]
Right now, teacher's are regularly putting in incomplete names. We want to have their full name, so we should split the Name Field into "First Name" and "Last Name" and then require both of them.

Also, as the teacher's name is student facing (they see it right on their profile) we should included a title field. This can have the options Mr., Miss, Mrs. Misses, Dr. and whatever else are standard ones. Then, we can display Mr. Smith instead of Tony Smith, which will probably be more appropriate for the students.

**Comment by SStrausman** [comment]
I'm going to work on this today.

**Comment by RyanNovas** [comment]
Hi @SStrausman, welcome to Quill!

It would be great if you joined our community page at [community.quill.org] (www.community.quill.org). From there you can join our chat (http://community.quill.org/chat/) and reach out to us with questions you may have.

**Comment by SStrausman** [comment]
Unsure as what this test is doing and how it is interacting with my code.

```
describe 'Sign up', :type => :request do
  describe 'Create New Teacher Account' do
    it 'requires unique email' do
      post '/account', user: user_params
      expect(response).to redirect_to(profile_path)

      post '/account', user: user_params
      expect(response).to_not redirect_to(profile_path)
      expect(response.body).to include('Email has already been taken')
    end
  end
```

I tried to add the following validation which is causing it to give the error:

     Failure/Error: expect(response).to redirect_to(profile_path)
       Expected response to be a <redirect>, but was <200>


The validation I was trying to add is:
```
  def first_name_validation
    if teacher?
      if first_name.nil? || first_name.empty?
        errors.add(:first_name, "can't be blank")
      end
    end
  end
```

I feel like perhaps I am missing something obvious here.

**Comment by bobmazanec** [comment]
From your description, I'd guess it's failing on

    expect(response).to redirect_to(profile_path)

Have you touched `user_params` at all?

If you haven't touched [`spec/support/helpers/session_helper.rb`](https://github.com/empirical-org/Empirical-Core/blob/develop/spec/support/helpers/session_helper.rb) or the `Hash`, I expect it's `POST`ing without (_i.e._, with `nil`) `first_name` param, which fails your validation instead of the usual 
[`redirect_to profile_path`](https://github.com/empirical-org/Empirical-Core/blob/develop/app/controllers/accounts_controller.rb#L27)

**Comment by petergault** [comment]
Marcello, want to follow up with @sstrausman?

**Comment by marcellosachs** [comment]
hi @SStrausman , I think the issue is that first_name and last_name are not params, the only param corresponding to name is just params[:name]. The database model does not have fields first_name and last_name, rather it just has a field name. The code in accounts_controller extracts a first_name and last_name from the params so that they can be capitalized before bringing them together to make 'name' (in user.rb, the method #first_name= and #last_name= brings them back together). I think the solution we need is to just check if the computed last_name is an empty string or not (after it is computed, so around this line https://github.com/empirical-org/Empirical-Core/blob/develop/app/controllers/accounts_controller.rb#L16)

**Comment by marcellosachs** [comment]
let me know if you have any questions...

**Comment by marcellosachs** [comment]
going to solve first_name, last_name validation now, and will hold off on adding 'title' until we get the new sign up pages implemented. going to split the 'title' issue into another issue....
