### ISSUE TITLE
Bug Report: Disappearing Concept Tags

### ISSUE THREAD

**Issue by rabhari** [empirical-org/Empirical-Core#4407]
https://docs.google.com/document/d/1vMXVZmm_6Ulph4LA2CxzaH8JLyRhk0F35vse2c5RNo0/edit?usp=sharing

**Comment by emilia-friedberg** [comment]
![screen shot 2018-09-17 at 11 29 58 am](https://user-images.githubusercontent.com/18669014/45633149-0e5d5780-ba6d-11e8-9aac-680885adcc9b.png)

Here is the state of the question in the bug report now. I cannot replicate this issue, so I am going to close it. It may have been inadvertently fixed by way of something else since this issue was created. If it reappears, please let us know.
