### ISSUE TITLE
Bug Report: Line break not happening in Quill Proofreader

### ISSUE THREAD

**Issue by tomcalabrese** [empirical-org/Empirical-Core#4556]
#### Expected Behaviour
If I add new words or characters to Quill Proofreader and it goes beyond the margin, it should break into the next line.

#### Actual Behaviour
[Screen recording](http://recordit.co/UmFQdta7Ky)
If I type a lot of additional words or characters into Quill Proofreader it does not create line breaks and instead keeps on going to the right indefinitely. 

#### Steps to Reproduce
Keep typing a bunch of characters/words until you notice the lack of line break.

**Comment by ddmck** [comment]
Thanks for pointing this out. This is one of the reasons @emilia-friedberg is rewriting it now. This issue should not be present based the way it is being implemented as one big text box rather than one per word (meaning they don't) break lines.

I'll probably close this tomorrow, but let me know how you would like me to handle this.
