### ISSUE TITLE
Teacher Dashboard Updates for Monday 

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#480]
Notes from the Scorebook:

1. When you delete a class, it should go back to the class manager page. 

2. There seems to be a bug where there is a large number of units (each activity is being split into its own unit). We should see if we can preserve the existing units, get them to group together. 
^ This is the serious bug. 

3. The header and footer need to be cleaned up. The footer is missing and the header needs to drop the “activities” and “news” section (they should be nested under about and community). Tom will put these together. 

4. The pagination should be limited to say the first 5 pages at the bottom of the screen. 

5. Marcello, Ryan and Peter need to work together to write a script that changes the names for the concepts and the 

6. The mouse over needs to get set up, and it needs to include the common core standards as a new field, in addition to the description. It should show the name, description, common core standards, and app name. 

7. The app names need to be fixed. 

8. Class Name seems to not update when pressing Save Changes. 

9. The class code text should be darker on the invite students page. 

10. Is the activity planner only showing activities flagged as Production? For example the activity “Hallowen, Yankees, New York” should be replaced with “Sentence Writing: “Capitalize Holidays, Product Names, and Geographic Names”. Right now it is showing both, it might be including the archived entries.

**Comment by marcellosachs** [comment]
@tomcalabrese research alert boxes/ notifications for these pages. 

-alert someone that they haven't created a unit title name.

**Comment by marcellosachs** [comment]
@petergault @tomcalabrese all has been taken care of except for : 

The header and footer need to be cleaned up. The footer is missing and the header needs to drop the “activities” and “news” section (they should be nested under about and community). Tom will put these together.

Marcello, Ryan and Peter need to work together to write a script that changes the names for the concepts and the

-----
Have not pushed most recent fixes since I'm waiting for peter's demo call to be over
