### ISSUE TITLE
Responses not loading in Grammar, Connect, and Diagnostic CMS

### ISSUE THREAD

**Issue by Hannahmonk** [empirical-org/Empirical-Core#5090]
**Describe the bug**
Student responses are not loading for questions in Connect, Diagnostic, and Grammar.
In Diagnostic, it says "Displaying 1-0 of 0 responses"
In Connect and Grammar, it says "Displaying 1-20 of undefined responses"

**To Reproduce**
1. Go to 
https://diagnostic.quill.org/#/admin/questions/-LVxjooFc8hOp5D5bxWv/responses
https://connect.quill.org/#/admin/questions/-Kua0Lrojrc-efmoD6kT/responses
https://beta-grammar.quill.org/#/admin/questions/-Jzw0qjJeHLqN6eDQTJl/responses

2. See no student responses

**Impact**
All three worked fine yesterday, so the problem seems to have begun last night or this morning.

**Comment by Hannahmonk** [comment]
Forgot to mention that I gave it about 15 minutes of loading time

**Comment by anathomical** [comment]
A previously-working CNAME pass-through for the CMS Elasticsearch connection began failing for no reason that we could determine.  We've resolved the issue for now by having the CMS connect directly to the AWS domain name for the Elasticsearch instance instead of going through a Quill-controlled CNAME.
