### ISSUE TITLE
Update Header for Discover Pages & Teacher Dashboard

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#515]
To Do:

1. Vlad will take the existing header for the teacher dashboard and apply the new colors. He will also update the logo and links. 
2. Vlad will apply the header to the discover pages. 
3. For the discover pages, we need the hierarchy for the following links: 

Discover
	About
		Mission (http://www.quill.org/mission)
		Community Development (http://www.quill.org/develop)
		Meet the Team (quill.org/about)
		FAQ (quill.org/faq) 
	Impact
		Statistics  http://www.quill.org/impact

Tweaks to each page: 
4. For the impact page (quill.org/impact), can we change the background color of this page to this color: rgb(240, 240, 240)
5. For the meet the team page (quill.org/about) Let's strip out everything above the words Meet the Team. 

# Long Term Tabs to Have
Long Term Links to have (ignore for now): 
Discover
	(Our Apps)
		(Browse All Activities / Explore Library) 
		(Quill Writer)
		(Quill Grammar)
		(Quill Proofreader) 
	About
		Mission (http://www.quill.org/mission)
		Community Development (http://www.quill.org/develop)
		Meet the Team (quill.org/about)
		FAQ (quill.org/faq) 
	Impact
		Statistics  http://www.quill.org/impact
		(Testimonials)
		(Tagboard)
	( Blog / News )
		( Press )
		( Educator Events
		( Developer Events )

**Comment by tomcalabrese** [comment]
#1. Update the Header

We’ve updated the header so that the color, the fonts, the logo, and the links have changed. We want to make sure the new header is on every page. Would you be able to take the current code and update it so it matches the current design? 

For example, the student page should have the new header. You can see the student page by going to Quill.org and signing with the username: Student, password: Student

The header has the following links: 
1. Discover links to quill.org/mission 
2. Community links to community.quill.org 	

https://drive.google.com/open?id=0B1RagCbDewKWczhERHZOX1BrbUU&authuser=0

https://drive.google.com/open?id=0B1RagCbDewKWY21fMUpaekV2bTA&authuser=0 for the student page. 

———

#2. Change the colors on the teacher dashboard menu 

We also want to update the teacher dashboard to update the new color and font style. For example you can go to: http://staging.quill.org/ login: Teacher password: Demo to see the current header and tab menu. Can you update this to match this psd. To be clear, this new design only changes the colors and fonts. The key change is that the fonts are all Adelle Sans, and the colors are updated. 

Teacher Dashboard: https://drive.google.com/open?id=0B1RagCbDewKWNHBYdE9ZaEpsNUU&authuser=0. 

———


#3. Update the “About” pages with the teacher dashboard. 
We would like these 5 pages to have the same tab style menu that the teacher dashboard has. For example, see this screenshot: 

mission quill.org/mission, meet the team quill.org/about, FAQ quill.org/faq, and community development quill.org/develop, statistics quill.org/impact.

We’re looking to have the tabs applied as follows: 

About
- Mission
- Community Development
- Meet the Team
- FAQ
Impact
- Statistics 

https://drive.google.com/open?id=0B1RagCbDewKWQlo5aWRtWFpnOW8&authuser=0. 	

———


In sum, for the navigation we need the following things:
- [ ] Every single page needs to have the new header, such as the sign up and sign in pages. 
- [ ] The teacher dashboard needs updated colors 
- [ ] The About pages need the header and footer.

**Comment by petergault** [comment]
Updates to static pages

1. For impact page (quill.org/impact) include it under the tab impact, sub-nav Statistics 
2. Change the background color of the page to #F0F0F0

3. For about us page, delete everything from the top of the page before the “meet the team section. 
4. Change the font to adelle sans. 

5. For the FAQ, change the font to adelle sans. 
6. Make the column width match the other pages.  (ask tom)
