### ISSUE TITLE
Alert: tell teachers they must assign a due date to assign activity

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#525]
On the second page of the activity planner, the "assign" button only pops up after the user sets a due date. We should show a message that states, "Select due dates to assign the unit." Once a user selects the due dates the message should disappear, and be replaced with the assign button.

**Comment by tomcalabrese** [comment]
1. I think ideally we should have an angular form validation for each element of a page. For instance when a user clicks the minimum amount of students in a classroom, in this instance it would be 1, the outline stroke around the box turns a different color, probably teal. And the 'assign activities' button would be grayed out until the reach the right amount of validated fields.

2. Or, I would have the 'assign activities' button the teal color, and if a user presses the submit button an alert box comes up and tells them what to do. Both of these are options in angular bootstrap. 

I don't think it's a good idea to remove the button completely with the message "Select due dates to assign the unit." because it might confuse them.

**Comment by petergault** [comment]
Hey so do we still need to do this? If so, let's make the button grey, and become green once the validations have been met.
