### ISSUE TITLE
Bug fixes for testimonial tab slider autoplay

### ISSUE THREAD

**Issue by knitevision1** [empirical-org/Empirical-Core#576]
Autoplay's default timer is 10 seconds

Before, it was like if you wait like X seconds of autoplay timer, then click on the tab, then the next autoplay timer will not be 10 seconds, it will be 10 - X.

So a lib developed a new version of the lib to fix that.

Just replace the content's of your tabslet.js with the contents of file jquery.tabslet.js from this archive https://github.com/vdw/Tabslet/releases/tag/v1.4.6

**Comment by marcellosachs** [comment]
It's not clear exactly which issue this was fixing.

One issue is the following (perhaps its identical to what vlad articulated) : 

If you click 'next' to go from the blue story to the red story at X seconds into the blue story, then the next time the blue story comes around, the blue story will begin at point X (and not at 0, the beginning of blue story).

Upon adding the new library, that issue was not solved.

There may be some other issue that this new library fixes, but I was unable to identify it.

**Comment by marcellosachs** [comment]
creating another issue to replace this
