### ISSUE TITLE
Lesson Planner page doesn't hide Assign when last student is unchecked

### ISSUE THREAD

**Issue by bobmazanec** [empirical-org/Empirical-Core#595]
**Given** I...
- am logged in as a Teacher
- have at least 1 class with at least 1 student
- am on Activity Planner | Create a Unit (`teachers/classrooms/lesson_planner`)
- have
 - supplied a name
 - selected at least 1 Activity
 - clicked Continue
- am on the "Select Students and Assign Dates for" 'page' where I...
 - have selected a Due Date
 - have _not_ checked any class' 'Select Entire Class' checkbox
 - have clicked a class' 'Select by Student'
 - have checked 1 student
 - can see the Assign button

**When** I uncheck the student (leaving no boxes checked)

**Then** the Assign button should disappear

Right now (696dbea), it disappears only if check then uncheck an 'Entire Class' checkbox

**Comment by petergault** [comment]
Good find!

**Comment by marcellosachs** [comment]
@petergault @tomcalabrese a question about this : 
If I select a class, should it automatically select every student in that class (put checks next to all of their names) ? Also, If I haven't selected a class yet, and then select a single student in a class, should there then appear a check next to the classroom name ?

**Comment by petergault** [comment]
Not sure about #1

For #2 no check in classroom. It indicates all students

**Comment by RyanNovas** [comment]
@petergault, @tomcalabrese and I were talking about this.

If I select a class, should it automatically select every student in that
class (put checks next to all of their names)?
- Yes, because by selecting a class, you have explicitly selected the
entire class. If all students are selected, then the Class box should check
itself.

On Tue, Mar 24, 2015 at 6:36 PM, Peter Gault <notifications@github.com>
wrote:

> Not sure about #1 <https://github.com/empirical-org/Empirical-Core/pull/1>
>
> For #2 <https://github.com/empirical-org/Empirical-Core/issues/2> no
> check in classroom. It indicates all students
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/empirical-org/Empirical-Core/issues/595#issuecomment-85720561>
> .
>



-- 
Ryan Novas
Director of Operations
Quill — Interactive Writing and Grammar

@Quill_Org <https://twitter.com/quill_org>

**Comment by marcellosachs** [comment]
fixed as of 4bf5804c054c7231f291da7c5cf0a1194ecaca28
