### ISSUE TITLE
Concepts and Standards by Student

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#599]
# Concept Tag per Student 
When a teacher clicks on a concept tag result, the teacher is brought to a page where the teachers sees all of the students listed for that concept result: 

https://moqups.com/gault8121/6RLG73bg/p:aac992f19
This page is showing the concept tag result for "It's"

# Standard Results per Student 

https://moqups.com/gault8121/6RLG73bg/p:a6b493fd7

**On each of these pages is a breadcrumbs function button that returns the user to the previous pages.**

**Comment by kriskelly** [comment]
@petergault Would you mind if the breadcrumbs appear above the filters? Also, is it an intentional decision that both the "Standards Summary" and "Grades Summary" views display the # of standards completed by students, but then you drill down to the "Students" subview and it would display the # of activities completed instead? Those are different numbers, just wanted to make sure that was an intentional decision, since it will require me to pull different numbers than for the parent views.
