### ISSUE TITLE
NoMethodError: undefined method `classrooms' for nil:NilClass

### ISSUE THREAD

**Issue by kriskelly** [empirical-org/Empirical-Core#664]
Error occurs in `teachers/units_controller.rb in index at line 47`

This line:

`cas = current_user.classrooms.map(&:classroom_activities).flatten`

Happening pretty frequently on production, not sure why, since teachers ought to be logged in at that point.

More info on Sentry:
https://app.getsentry.com/empirical-core/production/group/31311752/

**Comment by marcellosachs** [comment]
Seems its confined to about 10 users, all using IE  (81% are IE 8).
This error could be prevented by returning if current_user.nil? , though theoretically that should already be taken care of by the teacher! before_filter. Not sure if its best to implement that current_user.nil? line because that wouldn't be helping anyone - teachers that are logged in would just get no units instead of creating a sentry error, ... what's your opinion @kriskelly ?

**Comment by kriskelly** [comment]
Ideally I'd like to figure out why IE users are not appearing as logged in.
Maybe someone can fire up an IE8 VM and verify this error.

**Comment by kriskelly** [comment]
This error hasn't showed up in sentry in the past 3 months, doesn't seem necessary to fix it.
