### ISSUE TITLE
ActiveRecord::RecordInvalid: Validation failed: Username has already been taken

### ISSUE THREAD

**Issue by kriskelly** [empirical-org/Empirical-Core#665]
Happening in `teachers/students_controller.rb in create at line 21`

This line:

`@student.save!`

Happening pretty frequently on production.

More info on Sentry:
https://app.getsentry.com/empirical-core/production/group/31311752/

**Comment by marcellosachs** [comment]
This might be caused by the creation of a new student account for a student that has the same first and last name as another student in the same classroom (in which case they would be given identical usernames). I changed the generate_username method so that it appends a unique integer to the end of the last name within the username in such cases. If this problem persists then we'll know theres something else causing this. Also created an associated spec in user_spec.rb. Commit is e1d2cdcdd9896b89384a1888e72556b94785576e
