### ISSUE TITLE
ActionController::InvalidCrossOriginRequest: Security warning: an embedded <script> tag on another site requested protected JavaScript.

### ISSUE THREAD

**Issue by kriskelly** [empirical-org/Empirical-Core#670]
App is having Same Origin Request issues with the following URL:

`http://www.quill.org/ajax/libs/jquery-placeholder/2.0.8/jquery.placeholder.min.js`

This error makes exactly no sense to me, but the only reference to jquery.placeholder in the app is in the script tag in the application layout:

`script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/jquery-placeholder/2.0.8/jquery.placeholder.min.js"`

This error happens A LOT on production.

More info on Sentry:
https://app.getsentry.com/empirical-core/production/group/46084607/

**Comment by marcellosachs** [comment]
there are two things that could be done : 
1) include placeholder in the our own vendor folder of js libraries
2) remove placeholder because it is only needed for enabling placeholders in IE 9 and earlier and Opera mini (http://stackoverflow.com/questions/4004087/html-placeholder-browser-compatibility)

I'm gonna go with 2 for now.

**Comment by marcellosachs** [comment]
fixed as of 1321e654f50fbd4c740e9e9f33e45b8874c1e759
