### ISSUE TITLE
NoMethodError: undefined method `id' for nil:NilClass

### ISSUE THREAD

**Issue by kriskelly** [empirical-org/Empirical-Core#671]
In `classroom_activity.rb in session_for at line 26`

This is happening when the student assigns itself activity sessions, and it's happening on the profile page, `/profile`, which I don't quite understand.

More info from Sentry:
https://app.getsentry.com/empirical-core/production/group/60240454/

**Comment by marcellosachs** [comment]
@kriskelly this shouldn't get called on profile, but one thing that makes it a little bit less mysterious : 

if a student creates her own account, after doing so she is redirected to her profile page, and since she is not part of a classroom yet, the profile page that is shown is the 'join classroom' page. The 'join classroom' page references a partial, /teachers/classrooms/_activity.html.slim, in its display of 'activities you can demo' (which we wanted to remove, which I'll do with the forthcoming commit). This partial makes a call to session_for if @classroom is not nil. The thing is, @classroom should be nil in the case that no classroom has been joined yet, so session_for should never get called. However, perhaps one can imagine something messing up this logic. I'm going to remove the call to that partial and the partial itself (which now will not be used anywhere), and we'll see if the error persists on sentry...
