### ISSUE TITLE
Fix Broken Links - For Ryan & Marcello

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#687]
For Ryan
- [ ] Fix google ad words account so that it doesn't send people to quill.org/&/g

For Marcello
- [ ] Redirect users from this page to the homepage if they go there. 

@RyanNovas The google ad words manager is sending people to a broken page. You can fix it so that it doesn't do this. 
@marcellosachs You can set it up so that this page re-directs to the homepage. 

The 404 are from people landing on a mis spelled url for your homepage www.quill.org/&/g

These are the top 5 sources for this http://take.ms/MGzbc [Full referrer is the link that sent them there]. My guess is a typo in an ad destination url caused this.

**Comment by RyanNovas** [comment]
This does not seem to be from AdWords.

Here is the referring URL report. You will see that they are coming from a few specific URL's with the majority of them being refreshes of the /&/g page. As there have only been 18 unique page views, I don't think this issue is worth pursuing at this point.

![screen shot 2015-04-13 at 3 38 12 pm](https://cloud.githubusercontent.com/assets/6655439/7123867/241ccafc-e1f3-11e4-8a6b-258d0cf5437e.png)
