### ISSUE TITLE
UX Review - Feedback on the Quill.org homepage and Community pages

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#707]
Feedback on the Quill.org homepage and Community pages

We have recently launched a new homepage. However, we have received reports that users do not understand that they can scroll down from the homepage. 

For this issue, could you please explore our homepage, community pages, and discover pages, and provide feedback about the experience?

- [ ] What is missing?
- [ ] Is it intuitive?
- [ ] What would you like to see?

**Comment by a-sparks** [comment]
For the scrolling issue, add an arrow icon at the bottom right of the screen. The arrow could have a subtle animation to get the user's attention by bouncing up and down. The arrow would follow the user down the page as they scroll until they reach the bottom.

Other design and UX related suggestions include:

Email - Footer
Add a hyperlink to the email provided in the footer so that users can click on the email address and immediately contact Quill. Anytime the email appears on the website it should be hyperlinked.
Ex: Premium information page

Sign Up - Teacher
The alignment of the checkboxes is off.

Quill Logo - Sign Up & Login
Link the logo to the home page when on the Sign Up and Login pages. 

Tabs Hover State - Discover & Community
The hover state is inconsistent between the Discover and Community pages.
On the Community page, the tabs are missing the dark line at the top when the user hovers over them. Lines appear on the tabs under the Discover page.

Home Tab - Community
Keep the Home tab highlighted when the user selects menu items like Activity, Teams, etc. Other tabs stay highlighted, but Home does not.

Menu Items - Community
Keep the current menu item highlighted with an accent color so the users know where they are on the website.
Ex: On the Community page, if the user selects Activity under the Home tab, highlight the word "Activity."

Hero Images - Home
The hero images on the home page do not scale well on mobile devices. They should be responsive and adjust with the screen size.

Navigation - Support
The Support page does not have a navigation bar at the top of the page. This makes it difficult for the user to navigate to other pages.

Icons - Community Tabs
The resolution of the icons is not sharp under the tabs of the Community page. 
Ex: The text bubble icon under the Outreach tab. 
Consider using a font with scalable vector icons instead of images, like Font Awesome. 

Highlight - Discover & Community
Highlight the page the user is currently on, Discover or Community, on the navigation bar.

Activities Tab - Community
The menu item currently selected under the Activities tab doesn't have a gray box around it like the menu items under other tabs.

Navigation - News
The design of the News page's navigation isn't consistent with the other pages.

Zip Code - Teacher Sign Up
The text "Zip Code" is not fully visible in the input box on the Teacher Sign Up page.
To the right of this input box it says "Enter Your School's Zip Code," which is not the correct action that the user should be performing. This will likely confuse the user. The text could be replaced with "Select Your School." 

About - Discover
The About section feels hidden under the Discover page. It could be located in a more obvious spot, especially considering many first time users will be looking for this information. The About section could be moved to the main navigation bar at the top of the website.

Hyperlinks - About > Community Development
The hyperlinks blend in with the rest of the content on the page. These links could stand out more to the user by making the font slightly heavier in weight, using an accent color, or an underline.
