### ISSUE TITLE
"Uncaught RangeError: Maximum call stack size exceeded" mixpanel error on staging

### ISSUE THREAD

**Issue by kriskelly** [empirical-org/Empirical-Core#768]
Open up the developer console in Chrome to see this error while logged in as a teacher.

Haven't verified whether it's happening on production.

**Comment by marcellosachs** [comment]
Was caused by the fact that we had segment configured to include the mixpanel snippet, and then were including the mixpanel snippet itself at the same time. i changed our segment settings so that it is no longer configured to include mixpanel. It seems we would have to change the way our calls to mixpanel is written in order to complete an integration of mixpanel and segment, so for now we'll keep them separate.
see https://github.com/segmentio/analytics.js/issues/137
and https://segment.com/docs/integrations/mixpanel/
