### ISSUE TITLE
7. Make progress resports only accessible to users with subscription

### ISSUE THREAD

**Issue by marcellosachs** [empirical-org/Empirical-Core#793]
Not sure at what date this is supposed to begin, but we can implement it before that date and the flip the switch on the date.

**Comment by petergault** [comment]
To do this properly, we need to implement the following three states:

User=Premium
User = Trial.NoPremium
User=NoTrial.NoPremium 
(However you want to phrase it). 

# User=Premium
A user has premium if, in the LMS, the box has premium is activated. 
If a user has the premium service activated, that user sees the Progress Report page with:
- A star icon in place of where the beta tag was. (Use FontAwesome or an image if we are not yet using fontawesome). 
- Remove the static text bar that states: As a Quill early adopter you have premium access till X. 

![screen shot 2015-07-26 at 6 53 38 pm](https://cloud.githubusercontent.com/assets/3667179/8897554/128ec4b8-33cc-11e5-95de-9c3dd064f1fc.png)


# User=Trial.NoPremium. 
A teacher is on trial if: (1) the user does not have premium AND (2) the teacher has more activities completed than the "UserTrialLimit" variable. 
- The word "Beta" replaces trial. 
- In the orange bar, it states: As a Quill Premium trial user, you have free access for the first 250 student activities completed. 
- It shows a bar that states how far they are to 250 activities, and it shows the number. 

![screen shot 2015-07-26 at 7 28 23 pm](https://cloud.githubusercontent.com/assets/3667179/8897623/7a89f62c-33cd-11e5-8cf9-0aba0fafb786.png)


# User=NoTrial.NoPremium
A user is on "NoTrial.NoPremium" if the user: (1) does not have premium AND (2) the teacher has more activities completed than the "UserTrialLimit" variable. 
- Replace the text of the orange bar. 
- Create custom html for a page that loads instead of the progress reports. 
- The Learn More button should lead to https://www.quill.org/premium_access
- The orange button should have a padlock icon in it. 

![screen shot 2015-07-26 at 7 35 15 pm](https://cloud.githubusercontent.com/assets/3667179/8897641/c5810486-33cd-11e5-9b97-815745051e7c.png)


# UserTrialLimit Variable
This variable should be set at 250 now. In the future, if a user completes a certain action, such as tweeting about Quill, we will increase the user's limit. For now, we can keep it at 250 as a fixed amount.

**Comment by petergault** [comment]
Feel to access and edit these pages here:

https://moqups.com/#!/edit/gault8121/TdD3mFCk

**Comment by liyajames** [comment]
Does this have to be a table :( In the past when we've designed these report screens, teachers loved it when they can see things more visually...

**Comment by petergault** [comment]
@liyajames Yes we can have a larger conversation about the report screens. This issue is explictly about setting up a cap on the user's access to the reports. I'd love to think about this more, and we can set up a new issue to brainstorm new ways of visualizing the learning.

**Comment by petergault** [comment]
Done.
