### ISSUE TITLE
Google Sign-On -- 500 Error Bug

### ISSUE THREAD

**Issue by elliotmandel** [empirical-org/Empirical-Core#894]
Have gotten teacher issues coming in about students trying to sign in with their Google accounts.

It looks like 2 things are happening:
1. Students are having issues signing into Quill through Google once they've signed up
2. Teachers cannot edit the accounts of the students once they've used Google SSO

Teacher comments below:

1. One of my students is having trouble signing in with her Google Account.  She was able to sign up a few days ago, but now she is not able to get access.  I tried to edit her account but I get a 500 error message.  Please help? Thanks!

![error](https://cloud.githubusercontent.com/assets/12731246/9675622/f757b1ce-5274-11e5-97f6-8496ad60b905.png)

2. My students and I are having a little trouble.  I was alerted to this when one student who signed up using her google account pointed out that part of her last name was cut off.  When I looked at it from my end, it was the same thing.  Any of my students who signed up with Google don’t have usernames and I can’t edit their account (I get a 500 error), nor can I delete them from my class.

**Comment by kriskelly** [comment]
Here's the error in the logs:

```
2015-09-04T21:04:12.161921+00:00 app[web.1]: 
2015-09-04T21:04:12.161928+00:00 app[web.1]: BCrypt::Errors::InvalidHash (invalid hash):
2015-09-04T21:04:12.161930+00:00 app[web.1]:   app/controllers/teachers/students_controller.rb:24:in `edit'
2015-09-04T21:04:12.161931+00:00 app[web.1]: 
2015-09-04T21:04:12.161932+00:00 app[web.1]: 
2015-09-04T21:04:12.199629+00:00 app[web.1]: method=GET path=/500 format=html controller=teachers/students action=edit status=500 duration=36.86 view=30.15 db=6.06 params={"classroom_id"=>"11230", "id"=>"143898"}
```

**Comment by kriskelly** [comment]
My best guess is that this bug is due to Google SSO signups not assigning a password to the newly-created student accounts. That error in the `students_controller` seems due to a missing `password_digest` on the user account, so it would be best to either assign a password, make the user choose a password, or go through the code and prevent errors anywhere that the user is missing a password.

**Comment by marcellosachs** [comment]
not able to repo "Students are having issues signing into Quill through Google once they've signed up"
will try to repo the error involved in updating student accounts, and see if after causing that error the former one begins to occur

**Comment by kriskelly** [comment]
I can't remember the user ID for the student but try finding an account that is missing a password_digest value in the db. @marcellosachs

**Comment by marcellosachs** [comment]
@kriskelly I did use such a user. I was just now able to repo the 2nd problem of teachers not being able to edit student accounts, you were right - it was related to the app assuming students had a password here - https://github.com/empirical-org/Empirical-Core/blob/develop/app/controllers/teachers/students_controller.rb#L24

**Comment by marcellosachs** [comment]
was able to fix locally by 'conjuncting' a @student.password.present? at the start of the conditional

**Comment by marcellosachs** [comment]
@elliotmandel do we want the app to generate a username for a student when the student signs up through google? Up until now usernames were not required or generated if a student, when signing up, provided an email. In the case that a student account is created by a teacher (when the teacher 'invites' a student), we currently only ask the teacher to supply a first and last name, and using that we generate the username. We could generate a username in a similar fashion in this case if that is desired.

**Comment by marcellosachs** [comment]
decision - to indeed generate usernames

**Comment by marcellosachs** [comment]
In regards students not being able to sign in, it seems there are two related errors (with significant counts) on the server - 

one related to normal sign in : 
 https://rpm.newrelic.com/accounts/770600/applications/3825541/traced_errors/719164-11856eb0-5531-11e5-871a-c81f66b8ceca

one related to google sign in : 
https://rpm.newrelic.com/accounts/770600/applications/3825541/traced_errors/719164-6a696fde-5379-11e5-871a-c81f66b8ceca

**Comment by marcellosachs** [comment]
I'm looking at some of the users that specifically caused 1, and they indeed lack a password digest. 
It is unclear how this is occuring. It cannot be because they signed up through google and then tried to sign in regularly (mistakenly thinking this was possible), because the users I looked at did not have gmail emails. It also can't be because they are forgetting to input a password they sign up, because the form requires it. It also can't be because the site is not persisting the data, because I just tried myself and the site successfully persisted the data.

**Comment by marcellosachs** [comment]
This might give some insight into 2) - http://stackoverflow.com/questions/3364492/actioncontrollerinvalidauthenticitytoken

**Comment by marcellosachs** [comment]
going to split this into two issues

**Comment by marcellosachs** [comment]
now i found a user who does caused this error but does not have a blank password

**Comment by marcellosachs** [comment]
realized even though some of the emails arent gmails, they may be aliases over gmails

**Comment by marcellosachs** [comment]
Going to try to look at this case by case, first focusing on the cases where the user records have no recorded password. This could be caused by one of two things : 
1) users are creating accounts with google, then expecting to be able to sign in using our normal (non-google) sign in form
2) users are creating accounts in the traditional way, but the system is not storing their passwords

going to reach out to users to ask them

**Comment by marcellosachs** [comment]
on sept. 8th I implemented a fix which did the following - 

1) when a user tries to login, and the user corresponding to the inputted email has a blank password, an error message is returned suggesting that if the user signed up through google, that the user should also log in through google.

2) when a user signs up through google, makes an indication of that fact on the user record.

Since implementing that fix, the errors forming the subject of this issue have stopped occurring.
This indicates that it was only blank passwords which were instigating the BCRYPT error.

The question now is what is causing the blank passwords.
If everything is going right, then the blank passwords only occur on users who signed up through google. In this case, the BCRYPT errors were caused by users that had signed up through google but were trying to log in the traditional way.
However, it may be the case that blank passwords are created in cases where the user did not sign up through google (this would be a bug). This second case might explain why the blank-password-users are trying to sign in the traditional way.

Going to run a query to examine which users (since sept 8) have blank passwords and yet did not sign up through google, which should answer our question.

**Comment by marcellosachs** [comment]
Query results : 
3347 accounts created between the start of Sept. 9th and this moment
2501 of them were not through google
0 of the not-through-google accounts had a blank password

This seems to be pretty strong evidence that there is not a bug in the code giving blank passwords to users that did not sign up through google.
