### ISSUE TITLE
The activity flags are not working properly

### ISSUE THREAD

**Issue by petergault** [empirical-org/Empirical-Core#937]
The activity flags for `alpha`, `production`, and `archive` have commas after the name, which is causing the activities to be flagged under the wrong flag. When you flag it with these flags, it is now part of a different list. For example, `production,` is different than `production`. When you set an activity to `production` it shows on the site. However, without the flag it does not work. 

 https://www.quill.org/cms/activity_type/2/activities?flag=production%2C

![screen shot 2015-10-17 at 11 57 09 am](https://cloud.githubusercontent.com/assets/3667179/10560669/2d3cb09a-74c7-11e5-9c4a-7c3b74e23ad1.png)

**Comment by petergault** [comment]
![screen shot 2015-10-17 at 9 14 49 pm](https://cloud.githubusercontent.com/assets/3667179/10562032/e5281800-7514-11e5-93a8-42f6760b5cbe.png)
This is the value in the console.

**Comment by kriskelly** [comment]
I fixed this issue by removing the commas between the activity flags. The fix is on `master` as `develop` is currently broken. The second part involves correcting the bad data in the db or fixing it manually via the admin CMS form. That could easily be done by @marcellosachs or @ddmck, or manually by @petergault if you prefer.
